packages:
  - apps/*
  - packages/*

allowBuilds:
  # Replaces JS with the binary executable for optimizing: https://redirect.github.com/evanw/esbuild/issues/4085#issuecomment-2696009329
  esbuild: false
  # This package is used for converting images; Images are not used in this project
  sharp: false
  # Replaces JS with the binary executable for optimizing
  workerd: false
  # This package postinstall is used for legacy npm: https://github.com/unrs/unrs-resolver/blob/v1.11.1/README.md?plain=1#L12
  unrs-resolver: false
catalogs:
  build:
    '@cloudflare/vite-plugin': ^1.19.0
    '@tsconfig/vite-react': ^7.0.2
    '@vitejs/plugin-react': ^5.0.0
    vite: ^7.1.2
  dev:
    wrangler: ^4.56.0
  frontend:
    react: ^19.1.1
    react-dom: ^19.1.1
  lint:
    '@eslint/compat': ^2.0.0
    '@eslint/js': ^9.39.2
    '@stylistic/eslint-plugin': ^5.6.1
    eslint: ^9.33.0
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import: ^2.32.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    typescript-eslint: ^8.39.1
  node:
    globals: ^16.3.0
  test:
    '@tsconfig/strictest': ^2.0.8
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^25.0.3
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.7
